"""add delete behavior to models

Revision ID: 1865d2022460
Revises: 4a804634d503
Create Date: 2026-02-16 17:25:31.542058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1865d2022460'
down_revision: Union[str, Sequence[str], None] = '4a804634d503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
